kind: pipeline
name: images
type: kubernetes

steps:
- name: build
  image: zillownyc/drone-ecr:latest
  volumes:
  - name: dockersock
    path: /var/run
  environment:
    DOCKER_BUILDKIT: "1"
  settings:
    daemon_off: true
    purge: false
    repo: 253773679067.dkr.ecr.us-east-1.amazonaws.com/atlantis
    build_args:
    - BUILDKIT_INLINE_CACHE=true
    - ATLANTIS_VERSION=v0.10.1
    - SCENERY_VERSION=v0.1.5
    - TERRAGRUNT_VERSION=0.28.18
    - AWS_CLI_VERSION=1.18.54
    - ENVKEY_VERSION=latest
    cache_from:
    - 253773679067.dkr.ecr.us-east-1.amazonaws.com/atlantis:latest
    tags:
    - latest
    - "0.10.1"
    - "0.10"

trigger:
  event:
  - push
  - pull_request
  branch:
  - master


services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}
