kind: pipeline
name: images
type: kubernetes

steps:
- name: build
  image: plugins/docker
  environment:
  settings:
    purge: false
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: zillownyc/atlantis
    build_args:
    - ATLANTIS_VERSION=v0.10.1
    - SCENERY_VERSION=v0.1.5
    - TERRAGRUNT_VERSION=0.28.18
    - AWS_CLI_VERSION=1.18.54
    - ENVKEY_VERSION=latest
    tags:
    - latest
    - "0.10.1"
    - "0.10"

trigger:
  event:
  - push
  branch:
  - master
