kind: pipeline
name: images
type: kubernetes

steps:
- name: build
  image: plugins/docker
  volumes:
  - name: dockersock
    path: /var/run
  environment:
    DOCKER_BUILDKIT: "1"
  settings:
    daemon_off: true
    purge: false
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: zillownyc/atlantis
    build_args:
    - BUILDKIT_INLINE_CACHE=true
    - ATLANTIS_VERSION=v0.10.1
    - SCENERY_VERSION=v0.1.5
    - TERRAGRUNT_VERSION=0.28.24_tf0.14.10
    - AWS_CLI_VERSION=1.18.54
    - ENVKEY_VERSION=latest
    cache_from:
    - zillownyc/atlantis:latest
    tags:
    - latest
    - "0.10.1_tf14"
    - "0.10_tf14"

trigger:
  event:
  - push
  branch:
  - master

services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}

node:
  cluster: production-001
